[package]
  cjc-version = "1.2.0"
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
  description = "配合MVC使用的安全模块"
  link-option = ""
  name = "f_security"
  organization="fountain"
  output-type = "dynamic"
  src-dir = ""
  target-dir = ""
  version = "1.2.0"
  package-configuration = {}
  category = ["Utility", "Developer Tools", "Security"]
  license = ["Apache-2.0"]
  include = ["src", "doc"]
  exclude = ["cjpm.toml.bak", "cjpm.lock", "target"]
  authors = ["吴京润"]

[profile.build]
  incremental = true

[dependencies]
  "fountain::f_base" = {path = "../f_base"}
  "fountain::f_cache" = {path = "../f_cache"}
  "fountain::f_jwt" = {path = "../f_jwt"}
  "fountain::f_mvc" = {path = "../f_mvc"}


[target]
[target.x86_64-unknown-linux-gnu]
  compile-option = "--dy-std -Woff unused"
  override-compile-option = "--dy-std -Woff unused"
[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.aarch64-unknown-linux-gnu]
  compile-option = "--dy-std -Woff unused"
  override-compile-option = "--dy-std -Woff unused"
[target.aarch64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.x86_64-w64-mingw32]
  compile-option = "--dy-std -Woff unused"
  override-compile-option = "--dy-std -Woff unused"
[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.x86_64-apple-darwin]
  compile-option = "--dy-std -Woff unused"
  override-compile-option = "--dy-std -Woff unused"
[target.x86_64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.aarch64-apple-darwin]
  compile-option = "--dy-std -Woff unused"
  override-compile-option = "--dy-std -Woff unused"
[target.aarch64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.aarch64-linux-ohos]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"
[target.aarch64-linux-ohos.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.x86_64-linux-ohos]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"
[target.x86_64-linux-ohos.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]