[dependencies]
  charset4cj = { git = "https://gitcode.com/Cangjie-TPC/charset4cj.git", branch = "develop"}
  f_base  = {path = "../f_base", version = "1.0.45"}
  f_data  = {path = "../f_data", version = "1.0.45"}
  f_http  = {path = "../f_http", version = "1.0.45"}

[package]
  cjc-version = "1.0.4"
  compile-option = "-O2 --dy-std"
  override-compile-option = "-O2 --dy-std"
  description = "HTTP客户端"
  link-option = ""
  name = "f_httpclient"
  organization="fountain"
  output-type = "dynamic"
  src-dir = ""
  target-dir = ""
  version = "1.0.45"
  package-configuration = {}
  category = ["Utility"]
  license = ["Apache-2.0"]
  include = ["src"]
  authors = ["吴京润"]

[target]
[target.x86_64-unknown-linux-gnu]
  compile-option = "-O2 --lto=full --dy-std -ldl"
  override-compile-option = "-O2 --lto=full --dy-std -ldl"
[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.aarch64-unknown-linux-gnu]
  compile-option = "-O2 --lto=full --dy-std -ldl"
  override-compile-option = "-O2 --lto=full --dy-std -ldl"
[target.aarch64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.x86_64-w64-mingw32]
  compile-option = "-O2 --dy-std -lcrypt32"
  override-compile-option = "-O2 --dy-std -lcrypt32"
[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.x86_64-apple-darwin]
  compile-option = "-O2 --dy-std"
  override-compile-option = "-O2 --dy-std"
[target.x86_64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.aarch64-apple-darwin]
  compile-option = "-O2 --dy-std"
  override-compile-option = "-O2 --dy-std"
[target.aarch64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.aarch64-linux-ohos]
  compile-option = "-O2 --dy-std -ldl"
  override-compile-option = "-O2 --dy-std -ldl"
[target.aarch64-linux-ohos.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.x86_64-linux-ohos]
  compile-option = "-O2 --dy-std -ldl"
  override-compile-option = "-O2 --dy-std -ldl"
[target.x86_64-linux-ohos.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]

[profile.build]
  lto = "full"
  incremental = true
