# -*- coding: utf-8 -*-
"""25 个课程分册的定义：页码区间 + 首尾页文案 + 讲者备注"""

URL1 = 'https://pkg.cangjie-lang.cn/org/fountain'
URL2 = 'https://gitcode.com/Cangjie-SIG/fountain'

PARTS = [
    dict(a=1, b=8, title='开场与总体介绍',
         l1='为什么用 fountain：我们到底在重复哪五类劳动',
         l2='fountain 是什么：核心能力与外围模块全景',
         l3='课程地图与录制前的环境检查',
         cn='这是整套课程的第一讲，先解决「为什么要用」。我们写服务端，真正属于业务的代码很少，大量时间花在五类重复劳动上：对象怎么创建、接口开头那十几行校验、每张表重写 CRUD、事务边界靠人肉保证、以及每个项目重新选型。fountain 用四十多个模块把这些收干净。这一讲还会给你完整的课程地图，方便按需跳看。',
         e='这一讲是总纲。三个要点：一，服务端真正属于业务的代码很少，大量时间花在非业务复杂度上；二，fountain 把配置、IOC、AOP、数据、MVC、ORM、安全、日志、底座全部收进一个工具库；三，整套课程按 25 讲拆分，每讲十到十五分钟，可以按需跳看。',
         nxt='下一讲：三个设计决策与上台准备'),
    dict(a=9, b=15, title='三个设计决策与上台准备',
         l1='决策一：应用项目没有 main 函数',
         l2='决策二：宏为主、注解为辅　·　决策三：配置即环境变量',
         l3='什么时候不该用　·　环境准备　·　fboot 命令入口',
         cn='这一讲把 fountain 的三个反直觉设计决策一次讲完。第一，应用项目编译成动态链接库，由 fboot 扫描加载，代码里没有 main。第二，宏为主、注解为辅，能编译期解决的绝不留到运行期，反射只出现两次。第三，一切配置都是环境变量或命令行参数。然后坦白讲清楚什么场景不适合用，最后做上台准备。',
         e='这一讲的三个约定要记住：一，模块编译成动态链接库、由 fboot 加载启动——后面所有命令都建立在这条上；二，宏负责干活、注解负责声明；三，配置只有环境变量与命令行两个来源。另外四条「不该用」的理由也要心里有数：只支持仓颉、IOC 只管 class、依赖 stdx、宏的约定较硬。',
         nxt='下一讲：fboot 编译、启动与命令'),
    dict(a=16, b=21, title='fboot 编译、启动与命令',
         l1='fboot module 创建模块　·　fboot build 与两个隐藏动作',
         l2='编译期注入配置：连接串与口令如何嵌进产物',
         l3='fboot run 的八步启动流程　·　--dylibPattern 正则怎么读',
         cn='这一讲是纯操作。先说 fboot module 三件事，然后 fboot build——它不只转发给 cjpm build，还会生成版本模块、读 banner.txt，并把参数转成编译期环境变量，让连接串和口令以 SM4 密文嵌进产物。最后是 fboot run 的八步流程，重点在第三步：按 --dylibPattern 的正则加载动态链接库，这是全框架最容易踩的坑。',
         e='这一讲三个要点：一，fboot build 会把配置注入产物，产物目录规则是「路径等于当前目录时多一层目录名」；二，fboot run 加载动态链接库的顺序是扫描、加载、注册、拓扑排序、启动，而且它不会返回；三，凡是靠 @Bean 生效的东西，所在动态链接库都必须被 --dylibPattern 匹配到——鉴权器、切面、定时任务漏掉就是静默失效。',
         nxt='下一讲：f_config 配置体系（上）'),
    dict(a=22, b=27, title='f_config 配置体系（上）',
         l1='其余 fboot 命令与自定义子命令',
         l2='没有配置文件：四个来源与四级优先级',
         l3='命令行参数的四种写法　·　同一个写法，两个舞台　·　Config API',
         cn='这一讲先花几分钟把 fboot 的其余命令过完，包括自定义子命令的注册方式。然后进入第四章 f_config。先说结论：fountain 没有配置文件，配置只有四个来源。接着讲命令行参数的四种合法写法，以及为什么同一个写法在 fboot build 和 fboot run 两个舞台上的效果不同。最后是读取优先级与 Config API。',
         e='这一讲三个要点：一，配置只有四个来源，命令行参数覆盖同名环境变量；二，单数读取失败返回 None、复数读取失败抛异常，这个不对称一定要记住；三，命令行参数不是 fboot 的特权，任何链接了 f_config 的仓颉进程都会读自己的 argv。',
         nxt='下一讲：敏感配置与跑通 fdemo'),
    dict(a=28, b=33, title='敏感配置与跑通 fdemo',
         l1='敏感配置与 SM4 加密　·　@EmbedSensitive 的五条规则',
         l2='可配置的时间格式与两个已知问题',
         l3='现场跑通 fdemo：目录结构、建表、编译、启动',
         cn='这一讲先把第四章收尾：SM4 的六个参数怎么配、敏感值怎么加密嵌进产物、@EmbedSensitive 的五条嵌入规则，以及两个必须知道的已知问题。然后进入第五章，现场把 fdemo 跑起来——从目录结构讲到建表、编译、启动。注意 fdemo 的分包方式决定了动态链接库的粒度，这一点在做自己项目时要在设计阶段就定下来。',
         e='这一讲两个要点：一，敏感配置用 @EmbedSensitive 在编译期嵌入，注意 SM4 的参数本身也是明文写入产物的，这套机制抬高的是门槛而不是替代密钥管理；二，fdemo 的目录结构告诉我们「分包决定动态链接库粒度，粒度决定 --dylibPattern」，鉴权器和切面放哪个包是设计决策。',
         nxt='下一讲：接口验证与 IOC 入门'),
    dict(a=34, b=39, title='接口验证与 IOC 入门',
         l1='十二个接口的验收清单，其中 401 那一幕最关键',
         l2='f_bean 最小可用：@Bean + @BeanMeta',
         l3='lookup 家族　·　生命周期与构造注入',
         cn='这一讲先用十二个接口把 fdemo 的能力全部验一遍，其中第五步「不带 JWT 返回 401」是全场最直观的安全演示，建议留足时间。然后进入第二部分框架核心，先讲 IOC：@Bean 加可选的 @BeanMeta，宏展开后建三张索引表，所以可以用名字、类型、注解三种方式取 bean。接着是 lookup 家族与构造注入。',
         e='这一讲三个要点：一，fdemo 的十二个接口就是全套能力的验收清单，跑通了说明环境没问题；二，IOC 只管理 class 不管理 struct，这是明确的取舍；三，lookupList 一行拿到某接口的全部实现，是策略模式的免费实现，配合 BeanLabel 和 BeanWeight 还能做路由表。',
         nxt='下一讲：IOC 收尾与 AOP 全貌'),
    dict(a=40, b=45, title='IOC 收尾与 AOP 全貌',
         l1='条件装配：& | ! 可直接组合的条件对象',
         l2='AOP 的 Aspect 接口与默认执行顺序',
         l3='十四种织入规则　·　四个织入宏　·　两个杀手级用法',
         cn='这一讲先把 IOC 讲完：条件装配用 BeanCondition，与或非三个操作符都重载了，所以条件可以直接组合；然后在 fdemo 里看 IOC 的实际用法。接着进入 AOP：先看 Aspect 接口的六个方法和默认执行顺序，再逐条过十四种织入规则，最后讲四个织入宏和两个杀手级用法——事务与统一日志。',
         e='这一讲四个要点：一，切面的执行顺序由 proceed 编排，四步里任一步抛异常就进 throwing，而 final 一定执行；二，织入发生在切点函数首次被调用时，不是启动期，所以启动很快；三，切点表达式能从环境变量读，所以「哪些函数被切」是部署期可配的；四，事务切面就是 FuncAnnotationRouteRule 与 ConfigExecutionRouteRule 取或。',
         nxt='下一讲：f_data 数据模型与复制'),
    dict(a=46, b=51, title='f_data 数据模型与复制',
         l1='为什么先讲 f_data：它是 MVC / ORM / JWT 的共同底座',
         l2='@DataAssist 五个属性　·　props 展开为什么不破坏封装',
         l3='统一数据模型 Data　·　实例复制　·　DataConversionFlag',
         cn='这一讲进入第八章 f_data。先说清楚为什么先讲它——它是 MVC 参数绑定、ORM 结果映射、JWT 负载填充的共同底座。接着讲 @DataAssist 的五个属性，并用展开前后的对照说明 props 为什么不破坏封装。然后是统一数据模型：请求方向字节到 Data 再到对象，响应方向反过来。最后是实例复制的四种走法与 DataConversionFlag 这组容错旋钮。',
         e='这一讲三个要点：一，f_data 的统一数据模型是一棵树，任意两个类都能互转，因为都先落到 Data 上再长出来；二，props 靠宏生成属性访问器，不是反射，字段还是私有的；三，复制默认是 SILENCE——同名字段就复制、尽量转换、对不上的静默跳过，这是优点也是坑。',
         nxt='下一讲：f_data 收尾与 f_util 开场'),
    dict(a=52, b=56, title='f_data 收尾与 f_util 开场',
         l1='数据校验：一个注解 + 可组合的规则',
         l2='转换扩展、JSON Schema、JSONPath、快速失败',
         l3='f_util 全景　·　UUID 全版本　·　@IsUUID 与 IdMaker',
         cn='这一讲先把 f_data 讲完：十三个内置校验器可以用与或非组合，既能修饰成员也能修饰函数参数；然后是转换扩展、JSON Schema、JSONPath 查询和快速失败的 BreakingCommand。接着进入第九章 f_util，先给全景分类，再重点讲 UUID——它支持 v1 到 v8，而且实现了 DataFields，能直接当 PO 字段。最后是 @IsUUID 与雪花算法 IdMaker。',
         e='这一讲四个要点：一，校验器是 Validator 的子类，用与或非操作符组合，不是字符串表达式；二，UUID 的 v7 时间有序、适合做主键，而且天然能进 f_data 体系；三，IdMaker 的主机号必须全局唯一，否则会产生重复 ID；四，JSONPath 实现了 RFC 9535，路径带缓存。',
         nxt='下一讲：f_util 工具箱'),
    dict(a=57, b=61, title='f_util 工具箱',
         l1='CaseFormat 命名风格互转　·　TextTemplate 文本模板',
         l2='PathPattern：MVC 路由的引擎与匹配优先级',
         l3='TreeTransformer：平铺列表变树　·　三个设计模式骨架',
         cn='这一讲讲 f_util 的主体。CaseFormat 是六种命名风格两两互转，ORM 的列名转换底层用的就是它。TextTemplate 是文本模板，支持时间、数字、正则三种高级占位符。PathPattern 是 MVC 路由的引擎，匹配优先级从字符串相等一路排到跨多级双星。TreeTransformer 一行把平铺列表变成树。最后是三个现成的设计模式骨架。',
         e='这一讲四个要点：一，写代码生成器时用同一个 CaseFormat 枚举，命名风格才会和框架生成的一致；二，PathPattern 的优先级是「字符串相等最高、跨多级双星最低」，MVC 路由就靠它；三，TreeTransformer 只要节点类实现 TreeNode、提供 id 和 parentId 就够了；四，注意源码拼写是 Responsibility，少一个 n。',
         nxt='下一讲：MVC 路由与参数'),
    dict(a=62, b=66, title='MVC：路由与参数',
         l1='声明 Controller 与 Mapping 家族的三条规则',
         l2='params / headers 规则 DSL　·　五个参数绑定注解',
         l3='参数校验与安全注解　·　MVC 配置项',
         cn='这一讲进入第十章 MVC。先看声明 controller 的最小写法和三条规则，再讲 Mapping 家族的七个公共参数，以及 params 和 headers 那套规则 DSL——同一个路径可以根据带没带某些参数路由到不同函数。然后是五个参数绑定注解、参数校验与安全注解，最后是 MVC 的配置项，其中 mvc_maxRequestBodySize 做上传时必须调大。',
         e='这一讲四个要点：一，只有被星号 Mapping 注解修饰的公共实例函数才会注册到 MVC；二，@Controller 同时展开 @Bean，所以 controller 天然可以被 lookup；三，params 与 headers 的 DSL 参与路由匹配，匹配不上的请求根本不会进你的函数；四，放行有两种等价写法——@IgnoreSecurity 注解，或 Mapping 属性。',
         nxt='下一讲：MVC 收尾与 f_http'),
    dict(a=67, b=70, title='MVC 收尾与 f_http',
         l1='统一异常响应：三种 ErrorMessageKind',
         l2='重定向的四种状态码　·　当前请求上下文',
         l3='自定义 MediaType　·　f_http 的数据流向',
         cn='这一讲先把 MVC 收尾：统一异常响应的三种形态、重定向 301 与 302 与 307 与 308 的区别、以及用 CurrentHttpContext 在任何深度拿到当前请求。然后进入第十一章 f_http，关键是讲清楚数据流向——请求方向是字节到 Data 再到对象，响应方向反过来；MediaType 负责「字节和 Data」，f_data 负责「Data 和对象」。',
         e='这一讲三个要点：一，异常统一响应的 BEAN 取值是「bean 的名字」，这个 bean 必须实现 ErrorHttpRequestHandler；二，CurrentHttpContext 是线程级的，正因为它，鉴权逻辑才能写在 Service 层；三，f_mvc 里的 MediaType 就是 f_http 的类型，两者不是两套东西，f_mvc 那个文件只有一行 public import。',
         nxt='下一讲：f_http 扩展格式与上传'),
    dict(a=71, b=74, title='f_http 扩展格式与上传',
         l1='MediaTypes 注册表：加个 @Bean 就多一种数据格式',
         l2='自定义数据格式的完整六步清单',
         l3='文件上传的收发两侧　·　f_http 异常与排错',
         cn='这一讲把 f_http 讲完。先说 MediaTypes 注册表的两个来源——static init 内置注册，以及首次解析时从 IOC 拉取所有 MediaType bean，所以加个 @Bean 就多一种数据格式。然后是自定义格式的完整六步，漏一件就编译不过或匹配不上。接着是文件上传的收发两侧，最后是三个异常的排错思路。',
         e='这一讲三个要点：一，自定义 MediaType 的六步里，加 @Bean 是它被发现的唯一途径；二，报 is an illegal MediaType string，九成是 @Bean 没生效或所在动态库没被 --dylibPattern 匹配到；三，MultipartFile 是 Resource，用完必须 close，否则临时文件会在磁盘上堆积。',
         nxt='下一讲：ORM 的三个角色'),
    dict(a=75, b=78, title='ORM：三个角色',
         l1='PO：@QueryMappersGenerator 生成什么，@ORMField 的约束',
         l2='DAO：接口即实现，四条约束',
         l3='Service 与两条铁律',
         cn='这一讲进入第十二章 ORM，先把三个角色讲清楚。PO 上两个宏，@QueryMappersGenerator 会生成六样东西；DAO 最反直觉——@DAO 展开后没有实现类，SqlExecutor 本身就是实现，四条约束都是这句话的推论；Service 上要注意用 @TransactionalService 而不是 @Bean，否则事务不生效。最后是两条铁律。',
         e='这一讲四个要点：一，DAO 必须是接口且所有函数都要有默认实现，同一模块内函数名不能重名；二，每次调用 DAO 都要从 executor() 开始，不要把它存成变量；三，一个 DAO 函数只执行一个 SQL；四，PO 上的顺序约束是 @DataAssist 必须写在 @QueryMappersGenerator 之前。',
         nxt='下一讲：ORM 的 SQL 构造与分页'),
    dict(a=79, b=82, title='ORM：SQL 构造与分页',
         l1='ORM 配置项全表与两条 ARG 规则',
         l2='构造 SQL 的三种方式：模板 SQL、对象 DSL、条件构造器',
         l3='查询结果与分页：limit / offset 由方言生成',
         cn='这一讲是 ORM 的实操部分。先说配置项，注意全局是 orm 下划线 key、按驱动覆盖优先级更高。然后是构造 SQL 的三种方式：模板 SQL 加 arg 做参数绑定、对象 DSL 用 FROM 与 INSERT_INTO 与 UPDATE、条件构造器用 meet 与 WHERE 块处理动态条件。最后是查询结果的四类函数和分页的实现原理。',
         e='这一讲四个要点：一，arg() 做的是参数绑定，不存在字符串拼接注入；二，UPDATE 对象的 dirty 与 ignoredColumns 与 includingColumns 三个命名实参每次只能指定一个；三，WHERE 与 SET 块在内容为空时会自动省略关键字，不会拼出非法 SQL；四，分页的 limit 和 offset 由方言生成，换数据库不用改代码。',
         nxt='下一讲：事务控制与安全开场'),
    dict(a=83, b=87, title='事务控制与安全开场',
         l1='事务的三种开启方式与七种传播行为',
         l2='事务钩子的调用顺序　·　为什么同一线程共用连接',
         l3='ORM 的八个常见坑　·　登录状态检查怎么做',
         cn='这一讲是 ORM 最重的部分。先说事务的三种开启方式——注解、配置驱动、编程式，注解与配置是或的关系；再讲七种传播行为的语义；然后是七种事务钩子的调用顺序，五种场景我做成表格逐个对。接着讲清楚为什么同一线程共用连接，以及 ORM 的八个常见坑。最后开始第十三章，讲登录状态检查的第一步。',
         e='这一讲四个要点：一，注解与 orm_transactionalFuncExecution 配置是或关系，命中一个就织入事务；二、rollbackFor 是「发生它才回滚」，noRollbackFor 是「只有发生它才不回滚」，别记混；三，SqlExecutor 缓存在 ThreadLocal 里，这是事务能成立的根本；四，同一个 SqlExecutor 上不允许并发。',
         nxt='下一讲：安全与 JWT'),
    dict(a=88, b=91, title='安全与 JWT',
         l1='MVC 怎么挑 handler —— 第 3 步通过后第 4 步不执行',
         l2='用 JWT 维持登录状态：每个会话一把密钥',
         l3='f_jwt 的编码与解码 API　·　端到端演示',
         cn='这一讲把安全讲完。先讲 MVC 挑 handler 的五步顺序，这里有一个很重要的结论：第三步一旦通过就直接返回，第四步的权限检查不会执行，所以登录和权限最好在同一个类里一次检查完。然后是用 JWT 维持登录状态，以及 f_jwt 的编码与解码 API，最后用四步命令做端到端演示。',
         e='这一讲三个要点：一，AuthHandler 的挑选顺序决定了你的类该怎么设计，登录与权限分开实现会踩「权限检查没生效」这个坑；二，每个会话一把独立的 HMAC 密钥，即使某一把泄露也只影响一个会话；三，verify() 已经把 exp、nbf、签名都检查了，校验逻辑不用写在 controller 里。',
         nxt='下一讲：定时任务与日志开场'),
    dict(a=92, b=95, title='定时任务与日志开场',
         l1='f_ticktock：CRON 表达式与「静默失效」的坑',
         l2='日志：为什么还要自己写一个日志模块',
         l3='f_log 的三条纪律（先记这个）',
         cn='这一讲先用几分钟把定时任务讲完：实现 CronTicktockTask 加 @Bean 就够了，重点是 cron 表达式的七个时间位，以及那个「静默失效」的坑。然后进入第十五章日志。为什么还要自己写？因为 f_log 是 stdx.log 的实现，而且把全局 logger 接管了，第三方库的日志也会进你的 appender。最后是三条纪律。',
         e='这一讲三个要点：一，定时任务不执行，先查包有没有被 --dylibPattern 覆盖；二，f_log 默认静默，不配 appender 就没有任何输出；三，级别和格式挂在 appender 上，不挂在 logger 名字上——所以没有「只给某个包开 DEBUG」，来源靠格式里的 %name 区分。',
         nxt='下一讲：日志配置与异步管道'),
    dict(a=96, b=98, title='日志配置与异步管道',
         l1='配置项全表：一类 appender 挂若干具名实例',
         l2='三种写法与占位符全表',
         l3='一条日志的旅程：两级异步、两级队列',
         cn='这一讲是日志章节的主体。先过配置项全表——一类 appender 挂若干具名实例，实例各自配级别和格式。然后是三种写日志的方式：惰性 lambda、模板占位、异常写法，以及 pattern 里能用的占位符全表。最后是一条日志的旅程，这是全章最硬核的一节：业务线程只采集时间与线程 ID 然后入队，级别判断和渲染都在消费线程上。',
         e='这一讲四个要点：一，惰性 lambda 省的是渲染成本，不是排队成本；二，两级异步、两级队列，线程数约等于 logger 名字数加 appender 数；三，队列满时默认是「一直等」而不是丢日志，想丢要显式配 timeout 加 policy；四，%tid 在调用点采集、%tname 在写出时采集，排查问题请用 %tid。',
         nxt='下一讲：日志运维与速查'),
    dict(a=99, b=102, title='日志运维与速查',
         l1='文件切割与压缩的两个注意点',
         l2='现场把框架自己的日志调出来',
         l3='运行期刷新与八个坑　·　日志速查卡',
         cn='这一讲把日志收尾。先说文件切割与压缩：默认按天切，切完加时间后缀，配了压缩就压；两个注意点是不能配亚秒级的切割周期，以及压缩失败也会删掉原文件。然后是现场演示，把框架自己打的 SQL 和 access log 调出来看。最后是 LoggerFactory.refresh 能改哪些配置、哪些必须重启，以及那八个高频坑。',
         e='这一讲三个要点：一，rotateDuration 别配亚秒级，否则每次写日志都会 rename 加重开文件；二，%name 是定位问题的第一把钥匙，排查动作是「把级别调成 DEBUG，然后按 %name 去 grep」；三，refresh 最适合做的是调级别，缓冲区池大小只能重启。',
         nxt='下一讲：串讲与底座总览'),
    dict(a=103, b=104, title='串讲与底座总览',
         l1='一次 POST 请求穿过整个框架',
         l2='从 f_config 装载配置到落进日志文件的完整调用链',
         l3='框架之下的那一层：九个运行时模块总览',
         cn='这一讲分两半。前半是第十六章的串讲——用一个 POST 注册请求，从 f_config 装载配置开始，穿过 fboot 的动态链接库加载、MVC 路由、参数绑定、鉴权代理、切面、事务、ORM 执行，最后落进日志文件。后半是第十七章的开场，讲框架之下的那一层九个模块，以及每个模块被谁用了。',
         e='这一讲两个要点：一，串讲这一页就是 fountain 的全部——而你没有写过一个配置文件、没有写过一行 main，业务代码只有四个类；二，运行时基础设施九个模块的共同特点是零配置、可以单独引入、不绑架你的架构，就算不用 fountain 的框架部分，把它们当工具库用也完全没问题。',
         nxt='下一讲：运行时底座（一）'),
    dict(a=105, b=106, title='运行时底座（一）',
         l1='f_base：进程优雅退出与公共底座',
         l2='f_io 的 ByteBuffer 与 SyncByteBuffer',
         l3='f_cache 堆缓存与滑动续期　·　f_pool 对象池',
         cn='这一讲讲运行时底座的前四个模块。f_base 是所有模块脚下的那一层，重点是 ExitCallbacks 的进程优雅退出——按权重升序执行清理，所以 Ctrl-C 的顺序是先停服务、再关中间件、最后关数据库。然后是 f_io 的 ByteBuffer、f_cache 的堆缓存、f_pool 的对象池。',
         e='这一讲三个要点：一，f_cache 默认是滑动续期，要绝对过期就用 once；二，ORM 的 DatabasePool 就是 f_pool 的一个应用，两边手感完全一样；三，ByteBuffer 最常用的姿势是当内存输出目标，写完 bytes() 一次性取走。这一整章都可以按受众深浅整章跳过，不影响主线。',
         nxt='下一讲：运行时底座（二）'),
    dict(a=107, b=108, title='运行时底座（二）',
         l1='f_collection：BitSet、Dict 家族、顺序集合、集合运算视图',
         l2='f_time：TimeUnit 与 Int64 时间 DSL',
         l3='f_regex 正则缓存　·　f_rx 背压　·　f_random 随机数',
         cn='这一讲把运行时底座讲完。f_collection 挑四个解决痛点的：BitSet 是布隆过滤器的底座，Dict 家族把 hasher 和 equals 作为构造参数所以 key 不要求 Hashable，LinkedHashMap 离 LRU 只差一层封装，集合运算返回只读视图。然后是 f_time 的时间 DSL、f_regex 的正则缓存、f_rx 的背压策略，以及 f_random 与它那几条和直觉不一致的已知行为。',
         e='这一讲四个要点：一，热路径上反复编译正则是隐形 CPU 杀手，用 regex(solid) 走缓存；二，Dict 家族解决了「key 既不 Hashable 也不 Comparable」这个现实问题；三，背压只有固定线程池的策略才支持；四，f_random 的浮点 closed 可能超过上界、整数版会丢精度，(min,max) 重载有三处字符集与命名不符。',
         nxt='下一讲：高频坑与预设问答'),
    dict(a=109, b=112, title='高频坑与预设问答',
         l1='二十二个高频坑（第 1–11 条）',
         l2='二十二个高频坑（第 12–22 条）',
         l3='预设 Q&A：动态链接库、性能、单模块使用、配置管理',
         cn='这一讲是故障排查清单。二十二条坑逐条念，每条配一句原因和解法——这些是真实项目里最常撞的。后半段是预设问答：能不能不用动态链接库、性能如何、能不能只用一个模块、没有配置文件怎么管理几十个配置项、--key=value 是不是 fboot 的功能、build 和 run 上的配置有什么区别。',
         e='这一讲的重点不是记全二十二条，而是记住三条根因：一，凡是不生效的东西，先查所在动态链接库有没有被 --dylibPattern 匹配到；二，凡是「约定」类报错，都是宏的编译期约束，看报错信息就能定位；三，凡是配置不生效，按第四章的四级优先级逐层排查，别怀疑框架。',
         nxt='下一讲：速查表与收尾'),
    dict(a=113, b=116, title='速查表与收尾',
         l1='命令速查：日常真正反复敲的那几条',
         l2='配置速查：优先级、命令行写法、SM4、Config API、日志',
         l3='关键 API 速查　·　全课程收束',
         cn='这是最后一讲，三张速查表。第一张是 fboot 的命令，日常真正反复敲的就是那几条。第二张是配置，最上面是优先级规则，然后是命令行参数的四种写法、SM4 那一组、Config API，以及日志配置的三件事。第三张是关键 API，按模块分组。这三张表建议打印出来贴在显示器边上，需要细节时再回到对应那一讲。',
         e='整套课程到这里结束。如果只记一句话：fountain 的目标不是给你一个框架，而是把服务端的非业务复杂度整体收进工具库，让你的代码里只剩业务。全程没有配置文件、没有 main，业务代码只有四个类、两百行不到。三张速查表留在这一讲，平时开发直接翻这里就够了。',
         nxt='全课程到此结束 —— 感谢观看'),
]
