[package]
  cjc-version = "1.1.0"
  name = "f_mockdb"
  organization = "fountain"
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
  description = "mock database"
  version = "1.1.0"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  link-option = ""
  package-configuration = {}
  category = ["Utility"]
  license = ["Apache-2.0"]
  include = ["src"]
  authors = ["吴京润"]

[dependencies]
