[package]
  cjc-version = "1.0.4"
  name = "f_mockdb"
  compile-option = "-O2 --dy-std"
  override-compile-option = "-O2 --dy-std"
  description = "mock database"
  version = "1.0.44"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  link-option = ""
  package-configuration = {}

[dependencies]
