[dependencies]
  charset4cj = { git = "https://gitcode.com/Cangjie-TPC/charset4cj.git", branch="develop"}
  f_aspect = {path = "./f_aspect"}
  f_base = {path = "./f_base"}
  f_bean = {path = "./f_bean"}
  f_cache = {path = "./f_cache"}
  f_cmd = {path = "./f_cmd"}
  f_collection = {path = "./f_collection"}
  f_concurrent = {path = "./f_concurrent"}
  f_config = {path = "./f_config"}
  f_data = {path = "./f_data"}
  f_exception = {path = "./f_exception"}
  f_io = {path = "./f_io"}
  f_jwt = {path = "./f_jwt"}
  f_log = {path = "./f_log"}
  f_macros = {path = "./f_macros"}
  f_mvc = {path = "./f_mvc"}
  f_net = {path = "./f_net"}
  f_orm = {path = "./f_orm"}
  f_pool = {path = "./f_pool"}
  f_process = {path = "./f_process"}
  f_random = {path = "./f_random"}
  f_regex = {path = "./f_regex"}
  f_ticktock = {path = "./f_ticktock"}
  f_time = {path = "./f_time"}
  f_util = {path = "./f_util"}

[package]
  cjc-version = "1.0.0"
  compile-option = "-O2"
  description = "utility for server app development"
  link-option = ""
  name = "fountain"
  output-type = "dynamic"
  override-compile-option = "-O2"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[target.x86_64-w64-mingw32]
  [target.x86_64-w64-mingw32.bin-dependencies]
    path-option = ["${CANGJIE_STDX_PATH}/dynamic/stdx"]

[target.x86_64-unknown-linux-gnu]
  [target.x86_64-unknown-linux-gnu.bin-dependencies]
    path-option = ["${CANGJIE_STDX_PATH}/dynamic/stdx"]

[profile.build]
  lto = "full"
  incremental = true

[profile.build.combined]
  fountain = "dynamic"
