[dependencies]
  "cangjie_tpc::charset4cj" = "1.0.5"
  "fountain::f_app" = "1.1.0"
  "fountain::f_aspect" = "1.1.0"
  "fountain::f_base" = "1.1.0"
  "fountain::f_bean" = "1.1.0"
  "fountain::f_cache" = "1.1.0"
  "fountain::f_cmd" = "1.1.0"
  "fountain::f_codec" = "1.1.0"
  "fountain::f_collection" = "1.1.0"
  "fountain::f_concurrent" = "1.1.0"
  "fountain::f_config" = "1.1.0"
  "fountain::f_crypto" = "1.1.0"
  "fountain::f_data" = "1.1.0"
  "fountain::f_exception" = "1.1.0"
  "fountain::f_io" = "1.1.0"
  "fountain::f_jwt" = "1.1.0"
  "fountain::f_http" = "1.1.0"
  "fountain::f_httpclient" = "1.1.0"
  "fountain::f_log" = "1.1.0"
  "fountain::f_macros" = "1.1.0"
  "fountain::f_mockdb" = "1.1.0"
  "fountain::f_mvc" = "1.1.0"
  "fountain::f_net" = "1.1.0"
  "fountain::f_orm" = "1.1.0"
  "fountain::f_pool" = "1.1.0"
  "fountain::f_process" = "1.1.0"
  "fountain::f_random" = "1.1.0"
  "fountain::f_regex" = "1.1.0"
  "fountain::f_rx" = "1.1.0"
  "fountain::f_security" = "1.1.0"
  "fountain::f_ticktock" = "1.1.0"
  "fountain::f_time" = "1.1.0"
  "fountain::f_util" = "1.1.0"
  "fountain::f_version" = "1.1.0"

[package]
  cjc-version = "1.1.0"
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
  description = "utility for server app development"
  link-option = ""
  name = "fountain"
  organization = "fountain"
  output-type = "dynamic"
  src-dir = ""
  target-dir = ""
  version = "1.1.0"
  package-configuration = {}
  category = ["Utility"]
  license = ["Apache-2.0"]
  include = ["src"]
  exclude = ["cjpm.toml.bak", "cangjie.sh", ".gitignore", ".gitatributes", "CHANGELOG", "cjpm.lock", "target", ".modules"]
  authors = ["吴京润"] 

[target]
[target.x86_64-unknown-linux-gnu]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"
[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.aarch64-unknown-linux-gnu]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"
[target.aarch64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.x86_64-w64-mingw32]
  compile-option = "--dy-std -lcrypt32"
  override-compile-option = "--dy-std -lcrypt32"
[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.x86_64-apple-darwin]
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
[target.x86_64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.aarch64-apple-darwin]
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
[target.aarch64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.aarch64-linux-ohos]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"
[target.aarch64-linux-ohos.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.x86_64-linux-ohos]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"
[target.x86_64-linux-ohos.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]

[profile.build]
  incremental = true

#[profile.build.combined]
#  fountain = "dynamic"
