[dependencies]
  "cangjie_tpc::charset4cj" = "1.0.5"
  "fountain::f_app" = {path = "./f_app"}
  "fountain::f_aspect" = {path = "./f_aspect"}
  "fountain::f_base" = {path = "./f_base"}
  "fountain::f_bean" = {path = "./f_bean"}
  "fountain::f_cache" = {path = "./f_cache"}
  "fountain::f_cmd" = {path = "./f_cmd"}
  "fountain::f_codec" = {path = "./f_codec"}
  "fountain::f_collection" = {path = "./f_collection"}
  "fountain::f_concurrent" = {path = "./f_concurrent"}
  "fountain::f_config" = {path = "./f_config"}
  "fountain::f_crypto" = {path = "./f_crypto"}
  "fountain::f_data" = {path = "./f_data"}
  "fountain::f_exception" = {path = "./f_exception"}
  "fountain::f_io" = {path = "./f_io"}
  "fountain::f_jwt" = {path = "./f_jwt"}
  "fountain::f_http" = {path = "./f_http"}
  "fountain::f_httpclient" = {path = "./f_httpclient"}
  "fountain::f_log" = {path = "./f_log"}
  "fountain::f_macros" = {path = "./f_macros"}
  "fountain::f_mockdb" = {path = "./f_mockdb"}
  "fountain::f_mvc" = {path = "./f_mvc"}
  "fountain::f_net" = {path = "./f_net"}
  "fountain::f_orm" = {path = "./f_orm"}
  "fountain::f_pool" = {path = "./f_pool"}
  "fountain::f_process" = {path = "./f_process"}
  "fountain::f_random" = {path = "./f_random"}
  "fountain::f_regex" = {path = "./f_regex"}
  "fountain::f_rx" = {path = "./f_rx"}
  "fountain::f_security" = {path = "./f_security"}
  "fountain::f_ticktock" = {path = "./f_ticktock"}
  "fountain::f_time" = {path = "./f_time"}
  "fountain::f_util" = {path = "./f_util"}
  "fountain::f_version" = {path = "./f_version"}

[package]
  cjc-version = "1.1.0"
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
  description = "utility for server app development"
  link-option = ""
  name = "fountain"
  organization = "fountain"
  output-type = "dynamic"
  src-dir = ""
  target-dir = ""
  version = "1.1.3"
  package-configuration = {}
  category = ["Utility"]
  license = ["Apache-2.0"]
  include = ["src", "doc"]
  exclude = ["cjpm.toml.bak", "cangjie.sh", ".gitignore", ".gitatributes", "CHANGELOG", "cjpm.lock", "target", ".modules", "f_*", "fboot", "fdemo", "fcoder", "docs"]
  authors = ["吴京润"] 

[target]
[target.x86_64-unknown-linux-gnu]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"
[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.aarch64-unknown-linux-gnu]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"
[target.aarch64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.x86_64-w64-mingw32]
  compile-option = "--dy-std -lcrypt32"
  override-compile-option = "--dy-std -lcrypt32"
[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.x86_64-apple-darwin]
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
[target.x86_64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.aarch64-apple-darwin]
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
[target.aarch64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.aarch64-linux-ohos]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"
[target.aarch64-linux-ohos.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.x86_64-linux-ohos]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"
[target.x86_64-linux-ohos.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]

[profile.build]
  incremental = true

#[profile.build.combined]
#  fountain = "dynamic"
