[dependencies]
  f_base = {path = "../f_base"}
  f_collection = {path = "../f_collection"}
  f_exception = {path = "../f_exception"}
  
[package]
  cjc-version = "1.0.0"
  compile-option = "-O2 --dy-std"
  override-compile-option = "-O2 --dy-std"
  description = "nothing here"
  link-option = ""
  name = "f_cache"
  output-type = "dynamic"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[profile.build]
  lto = "full"
  incremental = true

[target]
[target.x86_64-unknown-linux-gnu]
  compile-option = "-O2 --lto=full --dy-std"
  override-compile-option = "-O2 --lto=full --dy-std"
[target.aarch64-unknown-linux-gnu]
  compile-option = "-O2 --lto=full --dy-std"
  override-compile-option = "-O2 --lto=full --dy-std"
[target.x86_64-w64-mingw32]
  compile-option = "-O2 --dy-std"
  override-compile-option = "-O2 --dy-std"
[target.x86_64-apple-darwin]
  compile-option = "-O2 --dy-std"
  override-compile-option = "-O2 --dy-std"
[target.aarch64-apple-darwin]
  compile-option = "-O2 --dy-std"
  override-compile-option = "-O2 --dy-std"