[dependencies]
  fountain = {path = "../"}
#  mysql = {git = "https://gitcode.com/Cangjie-TPC/mysqlclient-ffi.git"}
#  mysql = {git = "https://gitcode.com/runningW/mysql-driver.git"}
  opengauss = {git = "https://gitcode.com/runningW/opengauss-driver.git", branch="master"}

#[package]
#  cjc-version = "1.0.0"
#  compile-option = "-O2 --lto=full --dy-std"
#  override-compile-option = "-O2 --lto=full --dy-std"
#  description = "utility for server app development"
#  link-option = ""
#  name = "fountain"
#  output-type = "executable"
#  src-dir = ""
#  target-dir = ""
#  version = "1.0.0"
#  package-configuration = {}

[workspace]
  members=["./boot", "./user"]
  compile-option = "-O2 --lto=full --dy-std"
  override-compile-option = "-O2 --lto=full --dy-std"

[profile.build]
  incremental = true

[target]
[target.x86_64-w64-mingw32]
  compile-option = "-O2 --lto=full --dy-std"
  override-compile-option = "-O2 --lto=full --dy-std"
[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]

[target.x86_64-unknown-linux-gnu]
  compile-option = "-O2 --lto=full --dy-std"
  override-compile-option = "-O2 --lto=full --dy-std"
[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]

[target.aarch64-unknown-linux-gnu]
  compile-option = "-O2 --lto=full --dy-std"
  override-compile-option = "-O2 --lto=full --dy-std"
[target.aarch64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]

[target.x86_64-apple-darwin]
  compile-option = "-O2 --lto=full --dy-std"
  override-compile-option = "-O2 --lto=full --dy-std"
[target.x86_64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]

[target.aarch64-apple-darwin]
  compile-option = "-O2 --lto=full --dy-std"
  override-compile-option = "-O2 --lto=full --dy-std"
[target.aarch64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
