[dependencies]
  "fountain::fountain" = {path = "../"}
  "fountain::f_version" = {path = "../f_version"}
  # opengauss = {git = "https://gitcode.com/runningW/opengauss-driver.git", branch="master"}
#  opengauss = {path = "../../opengauss-driver"}
  pgsql = { git = "https://gitcode.com/aibrary/pgsql-driver.git", branch = "main" }

[workspace]
  version = "1.1.0"
  organization = "fountain"
  description = "demo for how to develop by fountain "
  members=["./boot", "./user"]
  compile-option = "-O2 --dy-std -Woff unused"
  override-compile-option = "-O2 --dy-std -Woff unused"

[profile.build]
  incremental = true

[target]
[target.x86_64-unknown-linux-gnu]
  compile-option = "-O2 --lto=full --dy-std -Woff unused"
  override-compile-option = "-O2 --lto=full --dy-std -Woff unused"
[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.aarch64-unknown-linux-gnu]
  compile-option = "-O2 --lto=full --dy-std -Woff unused"
  override-compile-option = "-O2 --lto=full --dy-std -Woff unused"
[target.aarch64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.x86_64-w64-mingw32]
  compile-option = "-O2 --dy-std -Woff unused"
  override-compile-option = "-O2 --dy-std -Woff unused"
[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.x86_64-apple-darwin]
  compile-option = "-O2 --dy-std -Woff unused"
  override-compile-option = "-O2 --dy-std -Woff unused"
[target.x86_64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.aarch64-apple-darwin]
  compile-option = "-O2 --dy-std -Woff unused"
  override-compile-option = "-O2 --dy-std -Woff unused"
[target.aarch64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.aarch64-linux-ohos]
  compile-option = "-O2 --dy-std -ldl"
  override-compile-option = "-O2 --dy-std -ldl"
[target.aarch64-linux-ohos.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.x86_64-linux-ohos]
  compile-option = "-O2 --dy-std -ldl"
  override-compile-option = "-O2 --dy-std -ldl"
[target.x86_64-linux-ohos.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]