[dependencies]
  "fountain::f_app" = { path = "../f_app" }
  "fountain::f_config" = { path = "../f_config" }
  "fountain::f_base" = { path = "../f_base" }
  "fountain::f_codec" = { path = "../f_codec" }
  "fountain::f_net" = { path = "../f_net" }
  "fountain::f_protocol" = { path = "../f_protocol" }
  "fountain::f_store" = { path = "../f_store" }
  "fountain::f_data" = { path = "../f_data" }
  "fountain::f_exception" = { path = "../f_exception" }
  "fountain::f_log" = { path = "../f_log" }
  "fountain::f_util" = { path = "../f_util" }

[package]
  cjc-version = "1.1.0"
  name = "fsync"
  description = "数据同步模块，可以用于配置、元数据注册等"
  target-dir = ""
  script-dir = ""
  output-type = "dynamic"
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
  organization = "fountain"
  version = "1.1.4"
  package-configuration = {}
  category = ["Utility"]
  license = ["Apache-2.0"]
  include = ["src", "doc"]
  exclude = ["cjpm.toml.bak", "cjpm.lock", "target"]
  authors = ["吴京润"]

[profile.build]
  incremental = true

[target]
[target.x86_64-unknown-linux-gnu]
  compile-option = "--dy-std -ldl -O2"
  override-compile-option = "--dy-std -ldl -O2"
[target.aarch64-unknown-linux-gnu]
  compile-option = "--dy-std -ldl -O2"
  override-compile-option = "--dy-std -ldl -O2"
[target.x86_64-w64-mingw32]
  compile-option = "--dy-std -lcrypt32"
  override-compile-option = "--dy-std -lcrypt32"
[target.x86_64-apple-darwin]
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
[target.aarch64-apple-darwin]
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
[target.aarch64-linux-ohos]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"
[target.x86_64-linux-ohos]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"
