[package]
  cjc-version = "1.0.4"
  name = "f_protocol"
  organization="fountain"
  description = "a protocol implementation"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  f_base = {path = "../f_base"}
  f_protocol = {path = "../f_protocol"}