[package]
  cjc-version = "1.1.0"
  name = "f_protocol"
  organization="fountain"
  description = "一个网络通讯协议实现"
  version = "1.1.4"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
  link-option = ""
  package-configuration = {}
  category = ["Utility"]
  license = ["Apache-2.0"]
  include = ["src", "doc"]
  exclude = ["cjpm.toml.bak", "cjpm.lock", "target"]
  authors = ["吴京润"]

[dependencies]
  "fountain::f_base" = {path = "../f_base"}
  "fountain::f_codec" = {path = "../f_codec"}
  "fountain::f_data" = {path = "../f_data"}
  "fountain::f_exception" = {path = "../f_exception"}
  "fountain::f_pool" = {path = "../f_pool"}