[package]
  cjc-version = "1.0.4"
  name = "f_protocol"
  organization="fountain"
  description = "a protocol implementation"
  version = "1.0.44"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  f_base = {path = "../f_base", version = "1.0.43"}
  f_codec = {path = "../f_codec", version = "1.0.43"}
  f_data = {path = "../f_data", version = "1.0.43"}
  f_exception = {path = "../f_exception", version = "1.0.43"}
  f_protocol = {path = "../f_protocol", version = "1.0.43"}
  f_pool = {path = "../f_pool", version = "1.0.43"}