[dependencies]
  "fountain::f_base" = {path = "../f_base"}
  "fountain::f_data" = {path = "../f_data"}
  "fountain::f_log" = {path = "../f_log"}
  "fountain::f_random" = {path = "../f_random"}
  "fountain::f_protocol" = {path = "../f_protocol"}

[package]
  cjc-version = "1.1.0"
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
  description = "事件驱动的网络通讯模块"
  link-option = ""
  name = "f_net"
  organization="fountain"
  output-type = "dynamic"
  src-dir = ""
  target-dir = ""
  version = "1.1.3"
  package-configuration = {}
  category = ["Utility"]
  license = ["Apache-2.0"]
  include = ["src", "doc"]
  exclude = ["cjpm.toml.bak", "cjpm.lock", "target"]
  authors = ["吴京润"]

[profile.build]
  incremental = true

[target]
[target.x86_64-unknown-linux-gnu]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"
[target.aarch64-unknown-linux-gnu]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"
[target.x86_64-w64-mingw32]
  compile-option = "--dy-std -lcrypt32"
  override-compile-option = "--dy-std -lcrypt32"
[target.x86_64-apple-darwin]
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
[target.aarch64-apple-darwin]
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
[target.aarch64-linux-ohos]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"
[target.x86_64-linux-ohos]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"