[dependencies]
  f_base = {path = "../f_base"}
  f_concurrent = {path = "../f_concurrent"}
  f_exception = {path = "../f_exception"}
  f_log = {path = "../f_log"}

[package]
  cjc-version = "0.60.5"
  compile-option = "-O2"
  description = "nothing here"
  link-option = ""
  name = "f_net"
  output-type = "dynamic"
  override-compile-option = "-O2"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
[profile.build]
  incremental = true