[package]
  cjc-version = "1.0.0"
  name = "boot"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  link-option = ""
  package-configuration = {}
