[package]
  cjc-version = "1.0.3"
  name = "f_app"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
 f_base = {path = "../f_base"}
 f_bean = {path = "../f_bean"}
 f_log = {path = "../f_log"}
 f_mvc = {path = "../f_mvc"}
 f_ticktock = {path = "../f_ticktock"}