[package]
  cjc-version = "1.2.0"
  name = "f_codec"
  organization="fountain"
  description = "编解码器"
  version = "1.2.0"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
  link-option = ""
  package-configuration = {}
  category = ["Utility"]
  license = ["Apache-2.0"]
  include = ["src", "doc"]
  exclude = ["cjpm.toml.bak", "cjpm.lock", "target"]
  authors = ["吴京润"]

[profile.build]
  incremental = true

[dependencies]
  "fountain::f_base" = {path = "../f_base"}
  "fountain::f_collection" = {path = "../f_collection"}
  "fountain::f_data" = {path = "../f_data"}
  "fountain::f_exception" = {path = "../f_exception"}
  "fountain::f_pool" = {path = "../f_pool"}
  "fountain::f_util" = {path = "../f_util"}