[package]
  cjc-version = "1.0.4"
  name = "f_codec"
  organization="fountain"
  description = "codec"
  version = "1.0.44"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  f_base = {path = "../f_base"}
  f_collection = {path = "../f_collection"}
  f_data = {path = "../f_data"}
  f_exception = {path = "../f_exception"}
  f_pool = {path = "../f_pool"}
  f_util = {path = "../f_util"}