/*
Copyright (c) 2025 WuJingrun（吴京润）

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package f_orm.sql

internal import std.collection.concurrent.ConcurrentHashMap
internal import f_collection.*
internal import f_exception.IllegalAccessException
internal import f_log.*
internal import f_regex.*
internal import f_orm.exception.*
internal import f_orm.{f_orm_getDirtyFields, f_orm_clear}

public import f_base.*
public import f_bean.*
public import f_data.*
public import f_orm.*

