/*
Copyright (c) 2026 WuJingrun（吴京润）

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package fountain::f_llm.constant

public type KnowledgeKind = String
public const KNOWLEDGE_KIND_STD = 'STD' 
public const KNOWLEDGE_KIND_API = 'API'
public const KNOWLEDGE_KIND_SYNTAX = 'SYNTAX'
public const KNOWLEDGE_KIND_EXPERIENCE = 'EXPERIENCE'
public const KNOWLEDGE_KIND_CODESPEC = 'CODESPEC'
public const KNOWLEDGE_KIND_ARTICLE = 'ARTICLE'
public const KNOWLEDGE_KIND_COPYRIGHT = 'COPYRIGHT'
public const KNOWLEDGE_KIND_SKILL_RESOURCE = 'SKILL_RESOURCE'
public const KNOWLEDGE_KIND_SKILL_REFERENCE = 'SKILL_REFERENCE'
public const KNOWLEDGE_KIND_SKILL_TOOL = 'SKILL_TOOL'
