[dependencies]
  f_io = {path = "../f_io"}
  f_regex = {path = "../f_regex"}
[package]
  cjc-version = "0.57.3"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "f_process"
  output-type = "dynamic"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
