[dependencies]

[package]
  cjc-version = "1.0.0"
  compile-option = "-O2"
  description = "nothing here"
  link-option = ""
  name = "f_base"
  output-type = "dynamic"
  override-compile-option = "-O2"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[profile.build]
  lto = "full"
  incremental = true
