[package]
  cjc-version = "1.1.0"
  name = "fcoder"
  organization = "fountain"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  script-dir = ""
  output-type = "executable"
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
  link-option = ""
  package-configuration = {}

[dependencies]
  f_base = {path = "../f_base"}
  f_bean = {path = "../f_bean"}
  f_data = {path = "../f_data"}
  f_egraph = {path = "../f_egraph"}
  f_log = {path = "../f_log"}
  f_orm = {path = "../f_orm"}
  f_version = {path = "../f_version"}