[dependencies]
  f_base = {path = "../f_base"}
  f_collection = {path = "../f_collection"}
  f_exception = {path = "../f_exception"}
  f_regex = {path = "../f_regex"}
[package]
  cjc-version = "0.57.3"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "f_data"
  output-type = "dynamic"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
