[dependencies]
  charset4cj = { git = "https://gitcode.com/Cangjie-TPC/charset4cj.git", branch = "develop", version = "0.0.1"}
  f_base = {path = "../f_base"}
  f_cache = {path = "../f_cache"}
  f_collection = {path = "../f_collection"}
  f_concurrent = {path = "../f_concurrent"}
  f_exception = {path = "../f_exception"}
  f_macros = {path = "../f_macros"}
  f_regex = {path = "../f_regex"}
  f_time = {path = "../f_time"}
[package]
  cjc-version = "0.57.3"
  compile-option = "-O2"
  description = "nothing here"
  link-option = ""
  name = "f_data"
  output-type = "dynamic"
  override-compile-option = "-O2"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
[profile.build]
  incremental = true