[dependencies]
  fountain = {path = "../"}

[package]
  cjc-version = "1.0.0"
  compile-option = "-O2"
  description = "fountain boot program"
  link-option = ""
  name = "fboot"
  output-type = "executable"
  override-compile-option = "-O2"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[profile.build]
  incremental = true
  lto = "full"

[target]
[target.x86_64-unknown-linux-gnu]
  compile-option = "-O2 --static --static-std --lto=full"
  override-compile-option = "-O2 --lto=full"
[target.aarch64-unknown-linux-gnu]
  compile-option = "-O2 --static --static-std --lto=full"
  override-compile-option = "-O2 --lto=full"
[target.x86_64-w64-mingw32]
  compile-option = "-O2 --static-std"
  override-compile-option = "-O2"
[target.x86_64-apple-darwin]
  compile-option = "-O2 --static-std"
  override-compile-option = "-O2"
[target.aarch64-apple-darwin]
  compile-option = "-O2 --static-std"
  override-compile-option = "-O2"