[dependencies]
# charset4cj = { git = "https://gitcode.com/Cangjie-TPC/charset4cj.git", branch = "develop", version = "0.0.1"}
# f_app = {path = "../f_app"}
# f_aspect = {path = "../f_aspect"}
# f_base = {path = "../f_base"}
# f_bean = {path = "../f_bean"}
# f_cache = {path = "../f_cache"}
# f_collection = {path = "../f_collection"}
# f_concurrent = {path = "../f_concurrent"}
# f_cron = {path = "../f_cron"}
  f_exception = {path = "../f_exception"}
# f_io = {path = "../f_io"}
# f_log = {path = "../f_log"}
# f_mvc = {path = "../f_mvc"}
# f_net = {path = "../f_net"}
# f_orm = {path = "../f_orm"}
# f_pool = {path = "../f_pool"}
# f_regex = {path = "../f_regex"}
# f_util = {path = "../f_util"}
  fountain = {path = "../"}

[package]
  cjc-version = "0.56.4"
  compile-option = ""
  description = "fountain boot program"
  link-option = ""
  name = "fboot"
  output-type = "executable"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
