[dependencies]
  fountain = {path = "../"}

[package]
  cjc-version = "1.0.4"
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
  description = "fountain boot program"
  link-option = ""
  name = "fboot"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.45"
  package-configuration = {}
  category = ["Utility"]
  license = ["Apache-2.0"]
  include = ["src"]
  authors = ["吴京润"]

[profile.build]
  incremental = true

[target]
[target.x86_64-unknown-linux-gnu]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"
[target.aarch64-unknown-linux-gnu]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"
[target.x86_64-w64-mingw32]
  compile-option = "--dy-std -lcrypt32"
  override-compile-option = "--dy-std -lcrypt32"
[target.x86_64-apple-darwin]
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
[target.aarch64-apple-darwin]
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
[target.aarch64-linux-ohos]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"
[target.x86_64-linux-ohos]
  compile-option = "--dy-std -ldl"
  override-compile-option = "--dy-std -ldl"