#!/bin/bash
###################################################################################
# File Name     : fboot
# Description   : fountain start script
# Language      : BASH
# Version       : 0.1
# Author        : 吴京润
# Created Time  : 2025-06-03 13:00 
###################################################################################

# fboot home variables define
PRG="$0"
PRG_DIR=`dirname "$PRG"`

[ -r $PRG ] || exit 5
[ -x $PRG ] || chmod u+x,g+x $PRG

if [ $1 -eq 'export' ]; then
    LD_PATH=`find $PRG_DIR -name 'f_*'|grep -v -P '\.so|\.cjo|\.build-logs'|tr '\n' ':'`
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LD_PATH
    export PATH=$PATH:$PRG_DIR/bin
else
    $PRG_DIR/bin/fboot start $1
fi
