[dependencies]
  f_data = {path = "../f_data"}
[package]
  cjc-version = "0.57.3"
  compile-option = "-O2"
  description = "nothing here"
  link-option = ""
  name = "f_mvc"
  output-type = "dynamic"
  override-compile-option = "-O2"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
[profile.build]
  incremental = true