[dependencies]
  f_base = {path = "../f_base"}
  f_collection = {path = "../f_collection"}

[package]
  cjc-version = "0.56.4"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "f_concurrent"
  output-type = "dynamic"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
