[package]
  cjc-version = "1.0.0"
  name = "launcher"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  boot = {path = "../boot"}
  user = {path = "../user"}

[target]
[target.x86_64-unknown-linux-gnu]
  compile-option = "-O2 --lto=full --dy-std"
  override-compile-option = "-O2 --lto=full --dy-std"
[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}", "${CANGJIE_FOUNTAIN_LIBS}"]
[target.aarch64-unknown-linux-gnu]
  compile-option = "-O2 --lto=full --dy-std"
  override-compile-option = "-O2 --lto=full --dy-std"
[target.aarch64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}", "${CANGJIE_FOUNTAIN_LIBS}"]
[target.x86_64-w64-mingw32]
  compile-option = "-O2 --dy-std"
  override-compile-option = "-O2 --dy-std"
[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}", "${CANGJIE_FOUNTAIN_LIBS}"]
[target.x86_64-apple-darwin]
  compile-option = "-O2 --dy-std"
  override-compile-option = "-O2 --dy-std"
[target.x86_64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}", "${CANGJIE_FOUNTAIN_LIBS}"]
[target.aarch64-apple-darwin]
  compile-option = "-O2 --dy-std"
  override-compile-option = "-O2 --dy-std"
[target.aarch64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}", "${CANGJIE_FOUNTAIN_LIBS}"]