[package]
  cjc-version = "1.2.0"
  name = "f_llm"
  organization = "fountain"
  description = "大模型驭缰工程，包含记忆保存与经验总结、函数、大模型访问、智能体定义，以及技能、智能体描述、经验查询"
  target-dir = ""
  script-dir = ""
  output-type = "dynamic"
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
  link-option = ""
  package-configuration = {}
  version = "1.2.2"
  category = ["Utility", "Developer Tools", "Programming Framework"]
  license = ["Apache-2.0"]
  include = ["src", "doc"]
  exclude = ["cjpm.toml.bak", "cjpm.lock", "target"]
  authors = ["吴京润"]

[dependencies]
  "fountain::f_aspect" = {path = "../f_aspect"}
  "fountain::f_base" = {path = "../f_base"}
  "fountain::f_bean" = {path = "../f_bean"}
  "fountain::f_config" = {path = "../f_config"}
  "fountain::f_data" = {path = "../f_data"}
  "fountain::f_egraph" = {path = "../f_egraph"}
  "fountain::f_httpclient" = {path = "../f_httpclient"}
  "fountain::f_log" = {path = "../f_log"}
  "fountain::f_macros" = {path = "../f_macros"}
  "fountain::f_orm" = {path = "../f_orm"}
  "fountain::f_regex" = {path = "../f_regex"}
  "fountain::f_store" = {path = "../f_store"}
  "fountain::f_time" = {path = "../f_time"}
  "fountain::f_util" = {path = "../f_util"}

[target]
[target.x86_64-unknown-linux-gnu]
  compile-option = "-O2 --dy-std -ldl"
  override-compile-option = "-O2 --dy-std -ldl"
[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.aarch64-unknown-linux-gnu]
  compile-option = "-O2 --dy-std -ldl"
  override-compile-option = "-O2 --dy-std -ldl"
[target.aarch64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.x86_64-w64-mingw32]
  compile-option = "-O2 --dy-std -lcrypt32"
  override-compile-option = "-O2 --dy-std -lcrypt32"
[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.x86_64-apple-darwin]
  compile-option = "-O2 --dy-std"
  override-compile-option = "-O2 --dy-std"
[target.x86_64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.aarch64-apple-darwin]
  compile-option = "-O2 --dy-std"
  override-compile-option = "-O2 --dy-std"
[target.aarch64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.aarch64-linux-ohos]
  compile-option = "-O2 --dy-std -ldl"
  override-compile-option = "-O2 --dy-std -ldl"
[target.aarch64-linux-ohos.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]
[target.x86_64-linux-ohos]
  compile-option = "-O2 --dy-std -ldl"
  override-compile-option = "-O2 --dy-std -ldl"
[target.x86_64-linux-ohos.bin-dependencies]
  path-option = ["${CANGJIE_STDX_DYNAMIC_PATH}"]

[profile.build]
  incremental = true