[dependencies]
  f_base = {path = "../f_base"}
  f_collection = {path = "../f_collection"}
  f_config = {path = "../f_config"}
  f_data = {path = "../f_data"}
  f_exception = {path = "../f_exception"}
  f_regex = {path = "../f_regex"}
  f_random = {path = "../f_random"}
  f_time = {path = "../f_time"}
[package]
  cjc-version = "0.57.3"
  compile-option = "-O2"
  description = "nothing here"
  link-option = ""
  name = "f_util"
  output-type = "dynamic"
  override-compile-option = "-O2"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[profile.build]
  incremental = true