[package]
  cjc-version = "1.2.0"
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
  description = "存储模块，包含依赖mmap的WAL和LSM-Tree"
  link-option = ""
  name = "f_store"
  organization="fountain"
  output-type = "dynamic"
  src-dir = ""
  target-dir = ""
  version = "1.2.2"
  package-configuration = {}
  category = ["Utility", "Developer Tools", "Object Storage"]
  license = ["Apache-2.0"]
  include = ["src", "doc"]
  exclude = ["cjpm.toml.bak", "cjpm.lock", "target"]
  authors = ["吴京润"]

[profile.build]
  incremental = true

[dependencies]
"fountain::f_base" = {path = "../f_base"}
"fountain::f_concurrent" = {path = "../f_concurrent"}
"fountain::f_bloom" = {path = "../f_bloom"}
"fountain::f_util" = {path = "../f_util"}
"fountain::f_collection" = {path = "../f_collection"}
"fountain::f_io" = {path = "../f_io"}