[package]
  cjc-version = "1.1.0"
  name = "f_store"
  organization = "fountain"
  description = "可持久化键值存储的薄封装，现在依赖的是badgercj"
  version = "1.1.2"
  target-dir = ""
  script-dir = ""
  output-type = "dynamic"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}
  category = ["Utility"]
  license = ["Apache-2.0"]
  include = ["src"]
  exclude = ["cjpm.toml.bak", "cjpm.lock", "target"]
  authors = ["吴京润"]

[dependencies]
  "badgercj" = "1.5.0"
  "fountain::f_base" = {path = "../f_base"}
  "fountain::f_codec" = {path = "../f_codec"}
  "fountain::f_data" = {path = "../f_data"}
