[package]
  cjc-version = "1.0.4"
  name = "user"
  description = "nothing here"
  version = "1.0.44"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = "-O2 --dy-std"
  override-compile-option = "-O2 --dy-std"
  link-option = ""
  package-configuration = {}
