CREATE EXTENSION zhparser;
CREATE TEXT SEARCH CONFIGURATION chinese_english (PARSER = zhparser);
ALTER TEXT SEARCH CONFIGURATION chinese_english ADD MAPPING FOR n,v,a,i,e,l WITH simple;
ALTER ROLE ALL SET zhparser.punctuation_ignore = ON;
ALTER ROLE ALL SET zhparser.multi_short = ON;
-----------------------------------------------------
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.update_time = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
----
CREATE OR REPLACE FUNCTION update_used_count()
RETURNS TRIGGER AS $$
BEGIN
    NEW.used_count = NEW.used_count + 1;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
----
create table llm_conf(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    llm_name varchar(16) not null,
    llm_type varchar(16) not null,
    llm_url varchar(128) not null,
    conf varchar(1024) not null,
    token_threshold bigint not null
);
alter table llm_conf add constraint pk_llm_conf primary key (id);
create unique index idx_llmconf_llm_name on llm_conf (llm_name);
comment on column llm_conf.llm_name is '大模型名称';
comment on column llm_conf.llm_type is 'llm类型text embedding rerank code video audio image';
comment on column llm_conf.llm_url is 'llm的URL';
comment on column llm_conf.conf is 'llm的配置信息';
comment on column llm_conf.token_threshold is 'token阈值，返回的总token数达到这个值说明上下文满了或者效果会明显下降';
----
create table llm_token_usage(
    id bigint generated by default as identity,
    llm_id bigint not null,
    agent_id bigint not null,
    skill_id bigint not null,
    prompt_tokens int not null,
    completion_tokens int not null,
    cached_tokens int not null,
    total_tokens int not null,
    usage_time bigint not null,
    save_time timestamptz not null default now()
);
alter table llm_token_usage add constraint pk_llm_token_usage primary key (id);
create unique index uk_llm_token_usage_llm_skill_usagetime on llm_token_usage(llm_id, agent_id, skill_id, usage_time);
comment on column llm_token_usage.llm_id is 'llm_conf.id';
comment on column llm_token_usage.agent_id is 'agents.id';
comment on column llm_token_usage.skill_id is 'skills.id';
comment on column llm_token_usage.prompt_tokens is '提示词的token数';
comment on column llm_token_usage.completion_tokens is '模型生成的token数';
comment on column llm_token_usage.cached_tokens is '缓存的token数';
comment on column llm_token_usage.total_tokens is '总token数';
comment on column llm_token_usage.usage_time is '记录tokens的时间，形式是yyyyMMddHHmm的整数';
comment on column llm_token_usage.save_time is '记录tokens的时间';
----
create table knowledge(
    id bigint GENERATED BY DEFAULT AS IDENTITY, 
    code_lang varchar(8) not null, 
    kind varchar(16) not null,
    md5 varchar(32) not null,
    source varchar(128) not null, 
    entire boolean not null,
    title varchar(255) NOT NULL,
    content text NOT NULL,
    used_count int NOT NULL,
    save_time timestamptz,
    update_time timestamptz,
    embedding VECTOR(1024)
);
ALTER TABLE knowledge ADD CONSTRAINT knowledge_pkey PRIMARY KEY (id);  
ALTER TABLE knowledge ADD COLUMN search_vector tsvector
GENERATED ALWAYS AS (
    setweight(to_tsvector('chinese_english', COALESCE(title, '')), 'A') ||
    setweight(to_tsvector('chinese_english', COALESCE(content, '')), 'B')
) STORED;
CREATE INDEX idx_knowledge_search_vector ON knowledge USING GIN(search_vector);
CREATE INDEX ON knowledge USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);
create index idx_knowledge_codelang on knowledge(code_lang, kind, source, entire);
create unique index uk_knowledge_md5 on knowledge (md5, code_lang, kind);
comment on column knowledge.code_lang is '代码文件的扩展名';
comment on column knowledge.kind is 'STD API SYNTAX EXPERIENCE CODESPEC ARTICLE COPYRIGHT SKILL_RESOURCE SKILL_REFERENCE SKILL_TOOL, STD、API、SYNTAX、CODESPEC和EXPERIENCE跟语言强相关，ARTICLE不一定跟语言相关，STD是标准库文档，API工具库文档，SYNTAX是语言特性，ARTICLE是技术文章，EXPERIENCE是犯过的错误、解决过的BUG、git提交的差异和提交信息的总结等，CODESPEC是代码规范，COPYRIGHT是版权声明，COPYRIGHT对应的code_lang是开源协议名，SKILL_RESOURCE是技能资源，SKILL_REFERENCE是技能参考资料，SKILL_TOOL是技能需要的工具';
comment on column knowledge.md5 is 'content的md5值，用于去重';
comment on column knowledge.source is '来源，对于STD API SYNTAX类型source的值就是版本号，对于ARTICLE source是URL，其它类型source是空字符串';
comment on column knowledge.entire is '是否整个文件，true：整个文档，false：只是一部分文档。把文档按标题拆分，方便只给llm提供需要的那部分';
comment on column knowledge.title is '对于SKILL_TOOL 此列是工具名';
comment on column knowledge.content is '对于SKILL_TOOL此列是JSON格式的工具描述{"description":"详细描述"，"parameters":[{"type":"DECIMAL", "properties":{"paramName":{"type":"DECIMAL", "decription":"参数的描述"},...}},...]}，SKILL_TOOL.params[].type是数据类型，可选值：DECIMAL STRING DATETIME DURATION BOOL OBJECT DECIMAL_ARRAY STRING_ARRAY DATETIME_ARRAY DURATION_ARRAY BOOL_ARRAY OBJECT_ARRAY；其它知识类型此列是markdown格式';
comment on column knowledge.save_time is '保存时间';
comment on column knowledge.update_time is '最后更新时间';
comment on column knowledge.used_count is '使用次数';
comment on column knowledge.embedding is '向量';
ALTER TABLE knowledge ALTER code_lang SET DEFAULT '';
ALTER TABLE knowledge ALTER kind SET DEFAULT '';
ALTER TABLE knowledge ALTER md5 SET DEFAULT '';
ALTER TABLE knowledge ALTER source SET DEFAULT '';
ALTER TABLE knowledge ALTER entire SET DEFAULT false;
ALTER TABLE knowledge ALTER used_count SET DEFAULT 0;
ALTER TABLE knowledge ALTER save_time SET DEFAULT now();
ALTER TABLE knowledge ALTER update_time SET DEFAULT now();
-- 最后更新时间触发器
CREATE TRIGGER trigger_knowledge_uptime 
BEFORE UPDATE ON knowledge
FOR EACH ROW 
EXECUTE FUNCTION update_modified_column();
----
create table projects (
    id bigint generated by default as identity,
    project_name varchar(32) not null,
    "description" varchar(1024) not null,
    save_time timestamptz not null default now()
);
CREATE UNIQUE INDEX idx_projects_name ON projects (project_name);
----
create table codes (
    id bigint generated by default as identity,
    project_id bigint,
    file_path varchar(128),
    module_name varchar(32),
    package_name varchar(128),
    code_lang varchar(8),
    code text,
    update_time timestamptz not null default now(),
    embedding VECTOR(1024)
);
--最后更新时间触发器
CREATE TRIGGER trigger_codes_uptime 
BEFORE UPDATE ON codes
FOR EACH ROW 
EXECUTE FUNCTION update_modified_column();
comment on column codes.file_path is '代码文件在项目中的相对路径';
ALTER TABLE codes ADD CONSTRAINT codes_pkey PRIMARY KEY (id);  
ALTER TABLE codes ADD COLUMN search_vector tsvector
GENERATED ALWAYS AS (
    to_tsvector('chinese_english', COALESCE(code, ''))
) STORED;
CREATE INDEX idx_codes_search_vector ON codes USING GIN(search_vector);
CREATE INDEX ON codes USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);
create index idx_codes_filepath on codes(project_id, file_path);
create index idx_codes_module on codes(project_id, module_name);
create index idx_codes_package on codes(project_id, package_name);
create index idx_codes_codelang on codes(project_id, code_lang);
----
create table specification (
    id bigint generated by default as identity,
    project_id bigint not null,
    code_lang varchar(8) not null,
    kind varchar(16) not null,
    title varchar(255) not null, 
    content text not null,
    update_time timestamptz not null,
    embedding VECTOR(1024)
);
ALTER TABLE specification ADD CONSTRAINT specification_pkey PRIMARY KEY (id);  
ALTER TABLE specification ADD COLUMN search_vector tsvector
GENERATED ALWAYS AS (
    setweight(to_tsvector('chinese_english', COALESCE(title, '')), 'A') ||
    setweight(to_tsvector('chinese_english', COALESCE(content, '')), 'B')
) STORED;
ALTER TABLE specification ALTER update_time SET DEFAULT now();
CREATE INDEX idx_specification_search_vector ON knowledge USING GIN(search_vector);
CREATE INDEX ON specification USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);
create index idx_specification_projectid_codelang_title on specification(project_id, code_lang, kind, title);
--最后更新时间触发器
CREATE TRIGGER trigger_specification_uptime 
BEFORE UPDATE ON specification
FOR EACH ROW 
EXECUTE FUNCTION update_modified_column();
comment on column specification.code_lang is '代码文件的扩展名';
comment on column specification.kind is '规范类型 CONSTITUTION FEASIBILITY REQUIREMENT PRELIMINARY DETAIL PLAN TASK';
----
create table skills (
    id bigint generated by default as identity,
    accepted_event varchar(16) not null, 
    returned_event varchar(16) not null,
    title varchar(64) not null,
    metadata varchar(1024) not null,
    details text not null,
    functions varchar(128) not null,
    skill_type varchar(8) not null,
    update_time timestamptz not null default current_timestamp
);
alter table skills add constraint skills_pkey primary key (id);
ALTER TABLE skills ALTER update_time SET DEFAULT now();
alter table skills alter functions SET DEFAULT '';
alter table skills alter skill_type set default 'primary';
create index uk_skills_accepted_event ON skills (accepted_event);
CREATE UNIQUE INDEX idx_skills_title ON skills (title);
comment on column skills.accepted_event is '技能接收的事件名称';
comment on column skills.returned_event is '技能返回的事件名称';
comment on column skills.skill_type is '技能类型，primary表示主技能，auxiliary表示辅助技能，主技能一直全部加载，辅助技能按需加载';
-- 最后更新时间触发器
CREATE TRIGGER trigger_skills_uptime 
BEFORE UPDATE ON skills
FOR EACH ROW 
EXECUTE FUNCTION update_modified_column();
----
create table agent_skills (
    id bigint generated by default as identity,
    agent_id bigint not null,
    skill_id bigint not null
);
alter table agent_skills add constraint agent_skills_pkey primary key (id);
create unique index idx_agent_skills_agent_skill on agent_skills (agent_id, skill_id);
----
create table problems (a
    id bigint generated by default as identity,
    context text not null,
    "description" varchar(255) not null,
    resolved boolean not null,
    save_time timestamptz not null
);
alter table problems add constraint problems_pkey primary key (id);
comment on column problems.context is '发现问题时的会话上下文';
ALTER TABLE problems ALTER resolved SET DEFAULT false;
ALTER TABLE problems ALTER save_time SET DEFAULT now();
----
create table organization (
    id bigint generated by default as identity,
    org_name varchar(32) not null,
    "description" varchar(1024) not null,
    culture text not null
);
alter table organization add constraint organization_pkey primary key (id);
create unique index idx_organization_name on organization (org_name);
comment on column organization.org_name is '组织名称';
comment on column organization.culture is '组织文化，用于描述组织风格';
----
create table agents (
    id bigint generated by default as identity,
    org_id bigint not null,
    agent_name varchar(16) not null,
    agent text not null,
    acceptable varchar(1024) not null,
    llm_type varchar(8) not null,
    llm_name varchar(16) not null
);
alter table agents add constraint agents_pkey primary key (id);
create unique index idx_agents_name on agents (agent_name);
create index idx_agents_org_id on agents (org_id);
comment on column agents.agent is '角色对应的agent名称';
comment on column agents.acceptable is '角色对应的agent可处理的问题类型，即事件名，多个事件用英文逗号隔开';
----
create table flows (
    id bigint generated by default as identity,
    category varchar(32) not null,
    tag varchar(32) not null,
    agent_id bigint not null,
    save_time timestamptz not null
);
alter table flows add constraint flows_pkey primary key (id);
create unique index idx_flows_category_tag on flows (category, tag, agent_id);
alter table flows alter save_time set default now();
comment on column flows.category is '流程名称';
comment on column flows.tag is '流程标签，相当于版本号';
comment on column flows.agent_id is '流程对应的agents.id';
----