CREATE EXTENSION zhparser;
CREATE TEXT SEARCH CONFIGURATION chinese_english (PARSER = zhparser);
ALTER TEXT SEARCH CONFIGURATION chinese_english ADD MAPPING FOR n,v,a,i,e,l WITH simple;
ALTER ROLE ALL SET zhparser.punctuation_ignore = ON;
ALTER ROLE ALL SET zhparser.multi_short = ON;
-----------------------------------------------------
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.update_time = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

create table llm_conf(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    llm_name varchar(16) not null,
    llm_type varchar(16) not null comment 'llm类型text embedding rerank code video audio image',
    llm_url varchar(128) not null,
    conf varchar(1024) not null comment 'llm的配置信息',
    token_threshold bigint not null comment 'token阈值，返回的总token数达到这个值说明上下文满了或者效果会明显下降',
);
alter table llm_conf add constraint pk_llm_conf primary key (id);
create unique index idx_llmconf_llm_name on llm_conf (llm_name);

create table llm_token_usage(
    id bigint generated by default as identity,
    llm_id bigint not null comment 'llm_conf.id',
    prompt_tokens int not null,
    completion_tokens int not null,
    cached_tokens int not null,
    total_tokens int not null,
    usage_time bigint not null comment '记录tokens的时间，形式是yyyyMMddHHmm的整数',
    save_time timestamptz not null default now(),
);
alter table llm_token_usage add constraint pk_llm_token_usage primary key (id);
create unique index uk_llm_token_usage_llmid_usagetime on llm_token_usage(llm_id, usage_time);

create table knowledge(
    id bigint GENERATED BY DEFAULT AS IDENTITY, 
    code_lang varchar(8) not null default '' comment '代码文件的扩展名', 
    kind varchar(16) not null default '' comment 'STD API SYNTAX EXPERIENCE CODESPEC ARTICLE COPYRIGHT SKILL_RESOURCE SKILL_REFERENCE SKILL_TOOL, STD、API、SYNTAX、CODESPEC和EXPERIENCE跟语言强相关，ARTICLE不一定跟语言相关，STD是标准库文档，API工具库文档，SYNTAX是语言特性，ARTICLE是技术文章，EXPERIENCE是犯过的错误、解决过的BUG、git提交的差异和提交信息的总结等，CODESPEC是代码规范，COPYRIGHT是版权声明，COPYRIGHT对应的code_lang是开源协议名，SKILL_RESOURCE是技能资源，SKILL_REFERENCE是技能参考资料，SKILL_TOOL是技能需要的工具',
    source varchar(128) not null default '' comment '来源，对于STD API SYNTAX类型source的值就是版本号，对于ARTICLE source是URL，其它类型source是空字符串', 
    entire boolean not null default false comment '是否整个文件，true：整个文档，false：只是一部分文档。把文档按标题拆分，方便只给llm提供需要的那部分',
    title varchar(255) NOT NULL comment '对于SKILL_TOOL 此列是工具名',
    content text NOT NULL comment '对于SKILL_TOOL此列是JSON格式的工具描述{"description":"详细描述"，"parameters":[{"type":"DECIMAL", "properties":{"paramName":{"type":"DECIMAL", "decription":"参数的描述"},...}},...]}，SKILL_TOOL.params[].type是数据类型，可选值：DECIMAL STRING DATETIME DURATION BOOL OBJECT DECIMAL_ARRAY STRING_ARRAY DATETIME_ARRAY DURATION_ARRAY BOOL_ARRAY OBJECT_ARRAY；其它知识类型此列是markdown格式',
    save_time timestamptz default now(),
    embedding VECTOR(2048)
);
ALTER TABLE knowledge ADD CONSTRAINT knowledge_pkey PRIMARY KEY (id);  
ALTER TABLE knowledge ADD COLUMN search_vector tsvector
GENERATED ALWAYS AS (
    setweight(to_tsvector('chinese_english', COALESCE(title, '')), 'A') ||
    setweight(to_tsvector('chinese_english', COALESCE(content, '')), 'B')
) STORED;
CREATE INDEX idx_knowlege_search_vector ON knowlege USING GIN(search_vector);
CREATE INDEX ON knowledge USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64, ef_search = 100);
create index idx_knowledge_codelang on specification(code_lang, kind, source, entire);

create table projects (
    id bigint generated by default as identity,
    project_name varchar(32) not null,
    "description" varchar(1024) not null,
    save_time timestamptz not null default now()
);
CREATE UNIQUE INDEX idx_projects_name ON projects (project_name);

create table codes (
    id bigint generated by default as identity,
    project_id bigint,
    file_path varchar(128) comment '代码文件在项目中的相对路径',
    module_name varchar(32)
    package_name varchar(128),
    code_lang varchar(8),
    code text,
    update_time timestamptz not null default now(),
    embedding vector(2048)
);
--最后更新时间触发器
CREATE TRIGGER trigger_codes_uptime 
BEFORE UPDATE ON codes
FOR EACH ROW 
EXECUTE FUNCTION update_modified_column();

ALTER TABLE codes ADD CONSTRAINT codes_pkey PRIMARY KEY (id);  
ALTER TABLE codes ADD COLUMN search_vector tsvector
GENERATED ALWAYS AS (
    to_tsvector('chinese_english', COALESCE(code, ''))
) STORED;
CREATE INDEX idx_codes_search_vector ON knowlege USING GIN(search_vector);
CREATE INDEX ON codes USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64, ef_search = 100);
create index idx_codes_filepath on specification(project_id, file_path);
create index idx_codes_module on specification(project_id, module_name);
create index idx_codes_package on specification(project_id, package_name);
create index idx_codes_codelang on specification(project_id, code_lang);

create table specification (
    id bigint generated by default as identity,
    project_id bigint not null,
    code_lang varchar(8) not null comment '代码文件扩展名',
    kind varchar(16) not null comment '规范类型 CONSTITUTION SPECIFY PLAN TASK',
    title varchar(255) not null, 
    content text not null,
    update_time timestamptz not null default now(),
    embedding VECTOR(2048)
);
ALTER TABLE specification ADD CONSTRAINT specification_pkey PRIMARY KEY (id);  
ALTER TABLE specification ADD COLUMN search_vector tsvector
GENERATED ALWAYS AS (
    setweight(to_tsvector('chinese_english', COALESCE(title, '')), 'A') ||
    setweight(to_tsvector('chinese_english', COALESCE(content, '')), 'B')
) STORED;
CREATE INDEX idx_specification_search_vector ON knowlege USING GIN(search_vector);
CREATE INDEX ON specification USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64, ef_search = 100);
create index idx_specification_projectid_codelang_title on specification(project_id, code_lang, kind, title);
--最后更新时间触发器
CREATE TRIGGER trigger_specification_uptime 
BEFORE UPDATE ON specification
FOR EACH ROW 
EXECUTE FUNCTION update_modified_column();

create table roles (
    id bigint generated by default as identity,
    role_name varchar(32) not null
);
alter table roles add constraint roles_pk primary key (id);
create unique index idx_roles_rolename on roles (role_name);

create table skills (
    id bigint generated by default as identity,
    role_id varchar(16) not null default 0 comment '可以不指定角色，指定了角色的技能只能由具体的角色agent加载',
    title varchar(64) not null,
    metadata varchar(1024) not null,
    details text not null,
    update_time timestamptz not null default current_timestamp,
);
alter table skills add constraint skills_pkey primary key (id);
ALTER TABLE skills ALTER update_time SET DEFAULT now();
ALTER TABLE skills ADD CONSTRAINT skills_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX idx_skills_title ON skills (title);

-- 最后更新时间触发器
CREATE TRIGGER trigger_skills_uptime 
BEFORE UPDATE ON skills
FOR EACH ROW 
EXECUTE FUNCTION update_modified_column();

create table problems (
    id bigint generated by default as identity,
    context text not null comment '发现问题时的会话上下文',
    "description" varchar(255) not null,
    resolved boolean not null default false,
    save_time timestamptz not null default now()
);
alter table problems add constraint problems_pkey primary key (id);
create unique index idx_tools_toolname on tools (tool_name);

create table agents (
    id bigint generated by default as identity,
    role_id bigint not null comment 'roles.id，此列为0时表示全局通用思想',
    agent text not null default ''
);
alter table agents add constraint agents_pkey primary key (id);
create unique index idx_agents_role_id on agents (role_id);
