[package]
  cjc-version = "1.0.4"
  name = "f_rx"
  description = "反应式编程"
  version = "1.0.45"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = "-O2 --dy-std"
  override-compile-option = "-O2 --dy-std"
  link-option = ""
  package-configuration = {}
  category = ["Utility"]
  license = ["Apache-2.0"]
  include = ["src"]
  authors = ["吴京润"]

[dependencies]
  f_base  = {path = "../f_base", version = "1.0.45"}
  f_concurrent  = {path = "../f_concurrent", version = "1.0.45"}

[profile.build]
  lto = "full"
  incremental = true

[target]
[target.x86_64-unknown-linux-gnu]
  compile-option = "-O2 --lto=full --dy-std -ldl"
  override-compile-option = "-O2 --lto=full --dy-std -ldl"
[target.aarch64-unknown-linux-gnu]
  compile-option = "-O2 --lto=full --dy-std -ldl"
  override-compile-option = "-O2 --lto=full --dy-std -ldl"
[target.x86_64-w64-mingw32]
  compile-option = "-O2 --dy-std -lcrypt32"
  override-compile-option = "-O2 --dy-std -lcrypt32"
[target.x86_64-apple-darwin]
  compile-option = "-O2 --dy-std"
  override-compile-option = "-O2 --dy-std"
[target.aarch64-apple-darwin]
  compile-option = "-O2 --dy-std"
  override-compile-option = "-O2 --dy-std"